# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{parallel}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2009-10-11}
  s.email = %q{grosser.michael@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/parallel.rb",
     "parallel.gemspec",
     "rdoc/README.rdoc",
     "spec/cases/parallel_each.rb",
     "spec/cases/parallel_influence_outside_data.rb",
     "spec/cases/parallel_map.rb",
     "spec/cases/parallel_map_sleeping.rb",
     "spec/cases/parallel_map_uneven.rb",
     "spec/cases/parallel_raise.rb",
     "spec/cases/parallel_sleeping_2.rb",
     "spec/cases/parallel_start_and_kill.rb",
     "spec/cases/parallel_with_detected_cpus.rb",
     "spec/cases/parallel_with_set_processes.rb",
     "spec/parallel_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/grosser/parallel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{parallel}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Run any kind of code in parallel processes}
  s.test_files = [
    "spec/parallel_spec.rb",
     "spec/spec_helper.rb",
     "spec/cases/parallel_raise.rb",
     "spec/cases/parallel_sleeping_2.rb",
     "spec/cases/parallel_start_and_kill.rb",
     "spec/cases/parallel_with_set_processes.rb",
     "spec/cases/parallel_influence_outside_data.rb",
     "spec/cases/parallel_map_sleeping.rb",
     "spec/cases/parallel_map_uneven.rb",
     "spec/cases/parallel_with_detected_cpus.rb",
     "spec/cases/parallel_map.rb",
     "spec/cases/parallel_each.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
