name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
    strategy:
      matrix:
        ruby: [ '3.3', '3.4', '4.0' ]
        task: [ 'spec' ]
        include:
        - ruby: 3.3 # keep in sync with lowest version
          task: rubocop
    name: ${{ matrix.ruby }} rake ${{ matrix.task }}
    env:
      BUNDLE_FROZEN: "false"
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake ${{ matrix.task }}
